spring.application.name=finance-tracker
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3307/FinanceTrackerDb
spring.datasource.username=TestUser
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt-secret=ec26dce5839b6c3f2bffc243c477bf173807ba14337d7dc30b17f0de74d79340
app.jwt-expiration-milliseconds=3600000
